"""add phone number

Revision ID: 613ca5ada0c6
Revises: 0a8c7242e59a
Create Date: 2023-07-14 20:15:54.518210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613ca5ada0c6'
down_revision = '0a8c7242e59a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
